apiVersion: v1
kind: Service
metadata:
  annotations:
  name: secc-api-service
  namespace: "9990227"
spec:
  ports:
  - name: http
    port: 1111
    protocol: TCP
    targetPort: 1111
  selector:
    app.kubernetes.io/name: secc-api
  type: ClusterIP
